baseurl = "https://karamaru-alpha.com"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "からまるのブログ"
theme = "tale"

[Author]
name = "karamaru"

[menu]
  [[menu.main]]
    identifier = "GitHub"
    name = "GitHub"
    title = "GitHub"
    url = "https://github.com/karamaru-alpha"
    weight = 1
  [[menu.main]]
    identifier = "X"
    name = "X"
    title = "X"
    url = "https://x.com/karamaru_alpha"
    weight = 2
  [[menu.main]]
    identifier = "SpeackerDeck"
    name = "SpeackerDeck"
    title = "SpeackerDeck"
    url = "https://speakerdeck.com/karamaru"
    weight = 3
  [[menu.main]]
    identifier = "SizuIn"
    name = "SizuIn"
    title = "SizuIn"
    url = "https://sizu.me/karamaru_alpha"
    weight = 4
  [[menu.main]]
    identifier = "LinkedIn"
    name = "LinkedIn"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/karamaru"
    weight = 5
  [[menu.main]]
    identifier = "RSS"
    name = "RSS"
    title = "RSS"
    url = "https://karamaru-alpha.com/index.xml"
    weight = 6

[Params]
toc = true
images = ["images/karamaru.jpg"]
