baseurl = "https://karamaru-alpha.com"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "からまるのブログ"
theme = "tale"

[Author]
name = "karamaru"

[menu]
  [[menu.main]]
    identifier = "twitter"
    name = "twitter"
    title = "twitter"
    url = "https://twitter.com/karamarooon"
    weight = 1
  [[menu.main]]
    identifier = "github"
    name = "github"
    title = "github"
    url = "https://github.com/karamaru-alpha"
    weight = 1

[Params]
toc = true
images = ["images/ren.png"]
