name: Hoge

on:
  pull_request:


jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
    - name: Collect Workflow Telemetry
      uses: catchpoint/workflow-telemetry-action@v1
